# 01-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: memos-db-secret
  namespace: memos
type: Opaque
stringData:
  POSTGRES_PASSWORD: "<YOUR_PASSWORD>"
  MEMOS_DSN: "postgres://memos:<YOUR_PASSWORD>@memos-postgres:5432/memos?sslmode=disable"

